### ISSUE TITLE
[FEATURE] The file tree shouldnt have anything in it if there is no workspace loaded

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#10]
**Is your feature request related to a problem? Please describe.**
Basically what the title says. This is confusing to users.

**Describe the solution you'd like**
The file tree should indicate that there is no workspace/folder open instead of the placeholder tree

**Additional context**
Deleting the data and just having it be an empty array should work I think

https://github.com/mellobacon/Nucleus/blob/a63f241504cde169be7984108f2bc5dd06ab912e/src/components/FileTree/TreeStore.ts#L3-L9

**Comment by mellobacon** [comment]
This will just be a temporary solution until I get around to having a proper place holder

**Comment by Suraj-Bhandarkar-S** [comment]
Working on this.
