### ISSUE TITLE
[FEATURE] Logging

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#108]
**Is your feature request related to a problem? Please describe.**
There is currently no longing implemented in the app.

**Describe the solution you'd like**
Add logging.

**Comment by Snehaaa18** [comment]
do you mean loging page or you want a log book ? also can I contribute in this project

**Comment by mellobacon** [comment]
> do you mean loging page or you want a log book ? also can I contribute in this project

Logging as in software logging. Part of it is already started so once I finish pushing the changes later today its open to be worked on.
