### ISSUE TITLE
[BUG] "yarn tauri dev" fails on Linux due to missing winreg crate

### ISSUE THREAD

**Issue by frankschmitt** [mellobacon/Nucleus#15]
**Describe the bug**
When trying to run ```yarn tauri dev``` on Ubuntu 20.04, it bails out with this error message:

> error: failed to run custom build command for `winreg v0.10.1`
>
>Caused by:
>  process didn't exit successfully: `/home/frank/src/3rd_party/Nucleus/src-tauri/target/debug/build/winreg-28dd1c04da324445/build-script-build` (exit status: 1)
>  --- stderr
>  error: winreg is only supported on Windows platforms
>  help: if your application is multi-platform, use `[target.'cfg(windows)'.dependencies] winreg = "..."`
>  help: if your application is only supported on Windows, use `--target x86_64-pc-windows-gnu` or some other windows platform

**To Reproduce**
- clone the repo on Linux (I'm using Ubuntu 20.04 LTS)
- run yarn tauri dev

**Expected behavior**
Development mode should start without errors

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.5 LTS

**Additional context**

**Comment by mellobacon** [comment]
Apologies, I must've forgotten to take the code for this out since it's not being used. 
This error is because of the `winreg` package which is used to access the windows registry so it makes sense for it not to work on linux. 

I'll get a fix out for this soon!

**Comment by mellobacon** [comment]
Alright hopefully this issue is fixed (see [commit](https://github.com/mellobacon/Nucleus/tree/db8d035535a05511a430f3b8f59b7a6db3419f7b)). I couldn't test fully since I had some issues with my linux installation but it did manage to build without errors.

Let me know if this works for you!

**Comment by frankschmitt** [comment]
Thanks, I'm able to build it now.
