### ISSUE TITLE
[FEATURE] Selecting an open tab should highlight the corresponding file in the file tree

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#18]
**Is your feature request related to a problem? Please describe.**
A file in the file tree doesnt highlight when you select a tab

**Describe the solution you'd like**
It would make it more clear what is selected if the file in the tree was highlighted like in other editors

**Comment by Savio629** [comment]
I would like to work on this issue. Can refer me some docs related to the issue or anything from which I can refer?

**Comment by mellobacon** [comment]
I don't have docs but I'm wanting something similar to the way Visual Studio Code highlights in the file tree. If you open multiple files and click on a tab, the file in the tree also highlights to show which one you selected.
