### ISSUE TITLE
[BUG] Tabs don't reorder

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#2]
**Describe the bug**
Tabs need to be able to be reordered. Currently that is attempting to be done via the sortable.js library, but it does not work for some reason. There are no errors.

Code being written here:
https://github.com/mellobacon/Nucleus/blob/6bd9a3b424024cb839019cd0513ac4d97c5b3958/src/components/Content/Editor/EditorTabs.svelte#L9-L16

**Comment by emotionalamoeba** [comment]
@mellobacon Mind if I take this one?

**Comment by mellobacon** [comment]
Of course, go ahead!

**Comment by ArrowAced** [comment]
The tabs can be reordered for me. (On Linux)

**Comment by mellobacon** [comment]
@ArrowAced I noticed this after you pointed it out. Led me to find a fix for the bug haha. Thanks for sharing!

**Comment by mellobacon** [comment]
@emotionalamoeba This issue has been fixed, but thanks for wanting to contribute!
