### ISSUE TITLE
[BUG] Tabs don't have names

### ISSUE THREAD

**Issue by ArrowAced** [mellobacon/Nucleus#26]
**Describe the bug**
Tabs do not have any names

**To Reproduce**
1. Open a tab
2. The tab won't have a name

**Expected behavior**
The tab should have a name

**Screenshots**
![image](https://user-images.githubusercontent.com/89811520/194729063-ea7cd670-e729-4b66-a7d8-b7c8ed8f2a48.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Additional context**
Everything else about tabs work

**Comment by mellobacon** [comment]
I've observed this bug as well. Haven't seen the problem just yet but I will get on this soon.

**Comment by mellobacon** [comment]
(Fixing this bug is open to others as well)
