### ISSUE TITLE
[FEATURE] External terminal support

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#31]
**Is your feature request related to a problem? Please describe.**
You are able to open a new terminal window from the editor. The way its done is spawning a new terminal based on a command, but that command depends on the OS.

**Describe the solution you'd like**
Different Linux distros has different commands for opening a terminal. Like `konsole`, `gnome-terminal`, etc. Since there is no automated way to check, it'll need to be done manually.

**Additional context**
This is how the code for opening a terminal works. As you can see right now it supports opening the Windows Terminal on Windows, and then support for opening the terminal on ubuntu/debian distros. What's needed is to basically have a list of known commands for opening the terminal on popular distros so that it's not limited to just one. There will also need to be a terminal command for MacOs.
https://github.com/mellobacon/Nucleus/blob/74d0f25688a8b482d21e40f52b185142aac8a3d6/src-tauri/src/main.rs#L27-L43

**Comment by auvalice** [comment]
Taking a look at this.

**Comment by auvalice** [comment]
Discussed; won't continue this. Internal is preferred
