### ISSUE TITLE
[BUG] File should be highlighted in file explorer

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#4]
**Describe the bug**
When you open a file or folder in the file explorer, its not highlighted, so its not obvious where it is.

**To Reproduce**
1. Open a folder or file
2. Right click on a file/folder in the file tree or open tab and click Open In Explorer
3. Once the file explorer shows up, it should open in the location the file is in, but it wont be highlighted in there

**Expected behavior**
After opening in the os file explorer, the file or folder should be highlighted so you don't have to go looking for it

**Comment by ish-u** [comment]
Hello,
I want to work on this Issue. I found this relevant Issue based on this Bug - https://github.com/tauri-apps/tauri/issues/4062.
We can use `invoke` function from tauri api in JS to call the rust function to call explorer with `select`

**Comment by mellobacon** [comment]
Oh awesome! I didn't know it was that easy haha.

 If you want to work on it free to open a pull request :)

**Comment by ish-u** [comment]
Okay I will create a PR
