### ISSUE TITLE
[FEATURE] Syntax Highlighting Themes

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#43]
**Is your feature request related to a problem? Please describe.**
The current code theme isn't too good

**Describe the solution you'd like**
There should be an improvement on that one or better yet a small list of themes to start with.

**Additional context**
There is a neat website for making a basic theme ([here](https://thememirror.net/)) for CodeMirror as well as some premade ones [here](http://farhadg.github.io/code-mirror-themes/) via https://github.com/FarhadG/code-mirror-themes. Making a custom one though would be nice for later.

**Comment by Snehaaa18** [comment]
please assign me this issue

**Comment by mellobacon** [comment]
I should add a note here. Syntax highlighting has not been added back after the rewrite yet. It might be a bit different from the original implementation so until the pieces are in place to add syntax highlighting back into the editor this issue should be on hold.

This will stay open for the future though and then updated once the feature can be added back.

**Comment by mellobacon** [comment]
From my research, syntax highlighting might be a bit difficult. Codemirror supports it but it doesnt support as many languages as other syntax highlighters out there. Also the syntax highlighting is more basic for performance reasons so it might not cover all the bases like more tokens being highlighted etc. With that said, Im looking into seeing if I can find a way to make this system better, either through Codemirror or a separate syntax highlighter on top of that. If anyone has ideas Im open to hear them.

**Comment by mellobacon** [comment]
Im going to be putting the basics in place for now and then see what happens after things are in place

**Comment by mellobacon** [comment]
Closing for now. Basic highlighting is in place.
