### ISSUE TITLE
[FEATURE] Themes

### ISSUE THREAD

**Issue by mellobacon** [mellobacon/Nucleus#53]
**Is your feature request related to a problem? Please describe.**
Editor themes

**Describe the solution you'd like**
Just for a start have a dark and a light theme

**Additional context**
This feature is already being worked on but is going to be postponed temporarily. Most likely it will work via JSON files instead of different stylesheets

**Comment by mellobacon** [comment]
Because I've been doing some reorganizing on my end. I saw it and will look it over in more depth once I get my code cleaned up. It's not a priority right now.

**Comment by athrvvvv** [comment]
but now I gonna work on this project very soon 💘

**Comment by mellobacon** [comment]
I have been busy with other things other than this project...but it hasn't been abandoned or anything. Though next time I'd appreciate an issue being opened before making a pr so that it can be discussed just in case.
